import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Globe2, PackageCheck, Truck, Warehouse } from 'lucide-react';
import { Reveal, SectionTitle } from '../components/UI';
import { brands, products, services, stats } from '../data/site';

export default function Home(){return <>
  <section className="hero"><div className="hero-grid container">
    <Reveal><span className="eyebrow gold">UAE TRADING & DISTRIBUTION</span><h1>Dependable products.<br/><em>Stronger partnerships.</em></h1><p>Three Star Traders LLC supports retailers, hospitality operators and commercial customers through reliable sourcing, distribution and responsive service.</p><div className="actions"><Link className="btn primary" to="/products">Explore products <ArrowRight size={18}/></Link><Link className="btn ghost" to="/contact">Become a partner</Link></div></Reveal>
    <Reveal delay={.15} className="hero-visual"><div className="visual-card main"><span>TRADE</span><strong>Built on reliability</strong><p>From product selection to final delivery, every step is designed around consistency.</p></div><div className="visual-card float one"><Truck/> Efficient delivery</div><div className="visual-card float two"><PackageCheck/> Quality selection</div></Reveal>
  </div></section>
  <section className="stats container">{stats.map((s,i)=><Reveal key={s.label} delay={i*.08}><strong>{s.value}</strong><span>{s.label}</span></Reveal>)}</section>
  <section className="section"><div className="container split"><Reveal><SectionTitle eyebrow="WHO WE ARE" title="A practical trading partner for growing businesses"/><p className="lead">We combine market understanding, disciplined fulfilment and personal service to help customers source the products they need with confidence.</p><ul className="checklist"><li><CheckCircle2/> Consistent product availability</li><li><CheckCircle2/> Clear commercial communication</li><li><CheckCircle2/> Flexible supply solutions</li><li><CheckCircle2/> Long-term supplier relationships</li></ul><Link className="text-link" to="/about">Discover our company <ArrowRight size={16}/></Link></Reveal><Reveal className="feature-panel"><div><Globe2/><h3>Connected sourcing</h3><p>Products and partners selected to match market demand.</p></div><div><Warehouse/><h3>Supply readiness</h3><p>Structured handling for wholesale and HORECA orders.</p></div></Reveal></div></section>
  <section className="section alt"><div className="container"><SectionTitle eyebrow="OUR CAPABILITIES" title="Services that move business forward" text="A focused portfolio for buyers, suppliers and brand owners."/><div className="cards three">{services.slice(0,6).map((s,i)=><Reveal key={s.title} delay={i*.05} className="card service-card"><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p></Reveal>)}</div></div></section>
  <section className="section"><div className="container"><div className="title-row"><SectionTitle eyebrow="PRODUCT PORTFOLIO" title="Selected for real market needs"/><Link className="text-link" to="/products">View all products <ArrowRight size={16}/></Link></div><div className="cards three">{products.slice(0,6).map((p,i)=><Reveal key={p.id} delay={i*.05} className="card product-card"><div className="product-icon">{p.name.charAt(0)}</div><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><span className="brand-pill">{p.brand}</span></Reveal>)}</div></div></section>
  <section className="brand-strip"><div className="container"><span>OUR PORTFOLIO</span>{brands.slice(0,6).map(b=><strong key={b}>{b}</strong>)}</div></section>
  <section className="cta"><div className="container"><Reveal><span className="eyebrow gold">LET'S WORK TOGETHER</span><h2>Looking for a dependable supply or distribution partner?</h2><p>Tell us what your business needs. Our team will review your enquiry and respond with the right next step.</p><Link className="btn primary" to="/contact">Send an enquiry <ArrowRight size={18}/></Link></Reveal></div></section>
</>}
